#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongViec
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyCongViec")]
	public partial class QLCV_DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertThanhVienNhomNhiemVu(ThanhVienNhomNhiemVu instance);
    partial void UpdateThanhVienNhomNhiemVu(ThanhVienNhomNhiemVu instance);
    partial void DeleteThanhVienNhomNhiemVu(ThanhVienNhomNhiemVu instance);
    partial void InsertDuAn(DuAn instance);
    partial void UpdateDuAn(DuAn instance);
    partial void DeleteDuAn(DuAn instance);
    partial void InsertMucDoQuanTrong(MucDoQuanTrong instance);
    partial void UpdateMucDoQuanTrong(MucDoQuanTrong instance);
    partial void DeleteMucDoQuanTrong(MucDoQuanTrong instance);
    partial void InsertMucDoUuTien(MucDoUuTien instance);
    partial void UpdateMucDoUuTien(MucDoUuTien instance);
    partial void DeleteMucDoUuTien(MucDoUuTien instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhiemVu(NhiemVu instance);
    partial void UpdateNhiemVu(NhiemVu instance);
    partial void DeleteNhiemVu(NhiemVu instance);
    partial void InsertNhom(Nhom instance);
    partial void UpdateNhom(Nhom instance);
    partial void DeleteNhom(Nhom instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertThanhVienNhom(ThanhVienNhom instance);
    partial void UpdateThanhVienNhom(ThanhVienNhom instance);
    partial void DeleteThanhVienNhom(ThanhVienNhom instance);
    partial void InsertThanhVienNhomDuAn(ThanhVienNhomDuAn instance);
    partial void UpdateThanhVienNhomDuAn(ThanhVienNhomDuAn instance);
    partial void DeleteThanhVienNhomDuAn(ThanhVienNhomDuAn instance);
    #endregion
		
		public QLCV_DBDataContext() : 
				base(global::QuanLyCongViec.Properties.Settings.Default.QuanLyCongViecConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLCV_DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCV_DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCV_DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCV_DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<ThanhVienNhomNhiemVu> ThanhVienNhomNhiemVus
		{
			get
			{
				return this.GetTable<ThanhVienNhomNhiemVu>();
			}
		}
		
		public System.Data.Linq.Table<DuAn> DuAns
		{
			get
			{
				return this.GetTable<DuAn>();
			}
		}
		
		public System.Data.Linq.Table<MucDoQuanTrong> MucDoQuanTrongs
		{
			get
			{
				return this.GetTable<MucDoQuanTrong>();
			}
		}
		
		public System.Data.Linq.Table<MucDoUuTien> MucDoUuTiens
		{
			get
			{
				return this.GetTable<MucDoUuTien>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhiemVu> NhiemVus
		{
			get
			{
				return this.GetTable<NhiemVu>();
			}
		}
		
		public System.Data.Linq.Table<Nhom> Nhoms
		{
			get
			{
				return this.GetTable<Nhom>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<ThanhVienNhom> ThanhVienNhoms
		{
			get
			{
				return this.GetTable<ThanhVienNhom>();
			}
		}
		
		public System.Data.Linq.Table<ThanhVienNhomDuAn> ThanhVienNhomDuAns
		{
			get
			{
				return this.GetTable<ThanhVienNhomDuAn>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChucVu;
		
		private string _TenChucVu;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChucVuChanging(string value);
    partial void OnMaChucVuChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    #endregion
		
		public ChucVu()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(30)")]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien", Storage="_NhanViens", ThisKey="MaChucVu", OtherKey="MaChucVu")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhVienNhomNhiemVu")]
	public partial class ThanhVienNhomNhiemVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _MaDuAn;
		
		private string _MaNhiemVu;
		
		private string _MaNhanVien;
		
		private EntityRef<DuAn> _DuAn;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<NhiemVu> _NhiemVu;
		
		private EntityRef<Nhom> _Nhom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnMaDuAnChanging(string value);
    partial void OnMaDuAnChanged();
    partial void OnMaNhiemVuChanging(string value);
    partial void OnMaNhiemVuChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    #endregion
		
		public ThanhVienNhomNhiemVu()
		{
			this._DuAn = default(EntityRef<DuAn>);
			this._NhanVien = default(EntityRef<NhanVien>);
			this._NhiemVu = default(EntityRef<NhiemVu>);
			this._Nhom = default(EntityRef<Nhom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._Nhom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					if (this._DuAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDuAnChanging(value);
					this.SendPropertyChanging();
					this._MaDuAn = value;
					this.SendPropertyChanged("MaDuAn");
					this.OnMaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhiemVu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhiemVu
		{
			get
			{
				return this._MaNhiemVu;
			}
			set
			{
				if ((this._MaNhiemVu != value))
				{
					if (this._NhiemVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._MaNhiemVu = value;
					this.SendPropertyChanged("MaNhiemVu");
					this.OnMaNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_ThanhVienNhomNhiemVu", Storage="_DuAn", ThisKey="MaDuAn", OtherKey="MaDuAn", IsForeignKey=true)]
		public DuAn DuAn
		{
			get
			{
				return this._DuAn.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn.Entity;
				if (((previousValue != value) 
							|| (this._DuAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn.Entity = null;
						previousValue.ThanhVienNhomNhiemVus.Remove(this);
					}
					this._DuAn.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhomNhiemVus.Add(this);
						this._MaDuAn = value.MaDuAn;
					}
					else
					{
						this._MaDuAn = default(string);
					}
					this.SendPropertyChanged("DuAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThanhVienNhomNhiemVu", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ThanhVienNhomNhiemVus.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhomNhiemVus.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhiemVu_ThanhVienNhomNhiemVu", Storage="_NhiemVu", ThisKey="MaNhiemVu", OtherKey="MaNhiemVu", IsForeignKey=true)]
		public NhiemVu NhiemVu
		{
			get
			{
				return this._NhiemVu.Entity;
			}
			set
			{
				NhiemVu previousValue = this._NhiemVu.Entity;
				if (((previousValue != value) 
							|| (this._NhiemVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhiemVu.Entity = null;
						previousValue.ThanhVienNhomNhiemVus.Remove(this);
					}
					this._NhiemVu.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhomNhiemVus.Add(this);
						this._MaNhiemVu = value.MaNhiemVu;
					}
					else
					{
						this._MaNhiemVu = default(string);
					}
					this.SendPropertyChanged("NhiemVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_ThanhVienNhomNhiemVu", Storage="_Nhom", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public Nhom Nhom
		{
			get
			{
				return this._Nhom.Entity;
			}
			set
			{
				Nhom previousValue = this._Nhom.Entity;
				if (((previousValue != value) 
							|| (this._Nhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom.Entity = null;
						previousValue.ThanhVienNhomNhiemVus.Remove(this);
					}
					this._Nhom.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhomNhiemVus.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("Nhom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuAn")]
	public partial class DuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDuAn;
		
		private string _TenDuAn;
		
		private string _MoTaDuAn;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDauDuAn;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThucDuAn;
		
		private System.Nullable<bool> _HoanThanhDuAn;
		
		private string _MaMucDoQuanTrong;
		
		private string _MaMucDoUuTien;
		
		private EntitySet<ThanhVienNhomNhiemVu> _ThanhVienNhomNhiemVus;
		
		private EntitySet<ThanhVienNhomDuAn> _ThanhVienNhomDuAns;
		
		private EntityRef<MucDoQuanTrong> _MucDoQuanTrong;
		
		private EntityRef<MucDoUuTien> _MucDoUuTien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDuAnChanging(string value);
    partial void OnMaDuAnChanged();
    partial void OnTenDuAnChanging(string value);
    partial void OnTenDuAnChanged();
    partial void OnMoTaDuAnChanging(string value);
    partial void OnMoTaDuAnChanged();
    partial void OnThoiGianBatDauDuAnChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauDuAnChanged();
    partial void OnThoiGianKetThucDuAnChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucDuAnChanged();
    partial void OnHoanThanhDuAnChanging(System.Nullable<bool> value);
    partial void OnHoanThanhDuAnChanged();
    partial void OnMaMucDoQuanTrongChanging(string value);
    partial void OnMaMucDoQuanTrongChanged();
    partial void OnMaMucDoUuTienChanging(string value);
    partial void OnMaMucDoUuTienChanged();
    #endregion
		
		public DuAn()
		{
			this._ThanhVienNhomNhiemVus = new EntitySet<ThanhVienNhomNhiemVu>(new Action<ThanhVienNhomNhiemVu>(this.attach_ThanhVienNhomNhiemVus), new Action<ThanhVienNhomNhiemVu>(this.detach_ThanhVienNhomNhiemVus));
			this._ThanhVienNhomDuAns = new EntitySet<ThanhVienNhomDuAn>(new Action<ThanhVienNhomDuAn>(this.attach_ThanhVienNhomDuAns), new Action<ThanhVienNhomDuAn>(this.detach_ThanhVienNhomDuAns));
			this._MucDoQuanTrong = default(EntityRef<MucDoQuanTrong>);
			this._MucDoUuTien = default(EntityRef<MucDoUuTien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this.OnMaDuAnChanging(value);
					this.SendPropertyChanging();
					this._MaDuAn = value;
					this.SendPropertyChanged("MaDuAn");
					this.OnMaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(30)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this.OnTenDuAnChanging(value);
					this.SendPropertyChanging();
					this._TenDuAn = value;
					this.SendPropertyChanged("TenDuAn");
					this.OnTenDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaDuAn", DbType="NVarChar(50)")]
		public string MoTaDuAn
		{
			get
			{
				return this._MoTaDuAn;
			}
			set
			{
				if ((this._MoTaDuAn != value))
				{
					this.OnMoTaDuAnChanging(value);
					this.SendPropertyChanging();
					this._MoTaDuAn = value;
					this.SendPropertyChanged("MoTaDuAn");
					this.OnMoTaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDauDuAn", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianBatDauDuAn
		{
			get
			{
				return this._ThoiGianBatDauDuAn;
			}
			set
			{
				if ((this._ThoiGianBatDauDuAn != value))
				{
					this.OnThoiGianBatDauDuAnChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDauDuAn = value;
					this.SendPropertyChanged("ThoiGianBatDauDuAn");
					this.OnThoiGianBatDauDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThucDuAn", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianKetThucDuAn
		{
			get
			{
				return this._ThoiGianKetThucDuAn;
			}
			set
			{
				if ((this._ThoiGianKetThucDuAn != value))
				{
					this.OnThoiGianKetThucDuAnChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThucDuAn = value;
					this.SendPropertyChanged("ThoiGianKetThucDuAn");
					this.OnThoiGianKetThucDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoanThanhDuAn", DbType="Bit")]
		public System.Nullable<bool> HoanThanhDuAn
		{
			get
			{
				return this._HoanThanhDuAn;
			}
			set
			{
				if ((this._HoanThanhDuAn != value))
				{
					this.OnHoanThanhDuAnChanging(value);
					this.SendPropertyChanging();
					this._HoanThanhDuAn = value;
					this.SendPropertyChanged("HoanThanhDuAn");
					this.OnHoanThanhDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMucDoQuanTrong", DbType="VarChar(10)")]
		public string MaMucDoQuanTrong
		{
			get
			{
				return this._MaMucDoQuanTrong;
			}
			set
			{
				if ((this._MaMucDoQuanTrong != value))
				{
					if (this._MucDoQuanTrong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMucDoQuanTrongChanging(value);
					this.SendPropertyChanging();
					this._MaMucDoQuanTrong = value;
					this.SendPropertyChanged("MaMucDoQuanTrong");
					this.OnMaMucDoQuanTrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMucDoUuTien", DbType="VarChar(10)")]
		public string MaMucDoUuTien
		{
			get
			{
				return this._MaMucDoUuTien;
			}
			set
			{
				if ((this._MaMucDoUuTien != value))
				{
					if (this._MucDoUuTien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMucDoUuTienChanging(value);
					this.SendPropertyChanging();
					this._MaMucDoUuTien = value;
					this.SendPropertyChanged("MaMucDoUuTien");
					this.OnMaMucDoUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_ThanhVienNhomNhiemVu", Storage="_ThanhVienNhomNhiemVus", ThisKey="MaDuAn", OtherKey="MaDuAn")]
		public EntitySet<ThanhVienNhomNhiemVu> ThanhVienNhomNhiemVus
		{
			get
			{
				return this._ThanhVienNhomNhiemVus;
			}
			set
			{
				this._ThanhVienNhomNhiemVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_ThanhVienNhomDuAn", Storage="_ThanhVienNhomDuAns", ThisKey="MaDuAn", OtherKey="MaDuAn")]
		public EntitySet<ThanhVienNhomDuAn> ThanhVienNhomDuAns
		{
			get
			{
				return this._ThanhVienNhomDuAns;
			}
			set
			{
				this._ThanhVienNhomDuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MucDoQuanTrong_DuAn", Storage="_MucDoQuanTrong", ThisKey="MaMucDoQuanTrong", OtherKey="MaMucDoQuanTrong", IsForeignKey=true)]
		public MucDoQuanTrong MucDoQuanTrong
		{
			get
			{
				return this._MucDoQuanTrong.Entity;
			}
			set
			{
				MucDoQuanTrong previousValue = this._MucDoQuanTrong.Entity;
				if (((previousValue != value) 
							|| (this._MucDoQuanTrong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MucDoQuanTrong.Entity = null;
						previousValue.DuAns.Remove(this);
					}
					this._MucDoQuanTrong.Entity = value;
					if ((value != null))
					{
						value.DuAns.Add(this);
						this._MaMucDoQuanTrong = value.MaMucDoQuanTrong;
					}
					else
					{
						this._MaMucDoQuanTrong = default(string);
					}
					this.SendPropertyChanged("MucDoQuanTrong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MucDoUuTien_DuAn", Storage="_MucDoUuTien", ThisKey="MaMucDoUuTien", OtherKey="MaMucDoUuTien", IsForeignKey=true)]
		public MucDoUuTien MucDoUuTien
		{
			get
			{
				return this._MucDoUuTien.Entity;
			}
			set
			{
				MucDoUuTien previousValue = this._MucDoUuTien.Entity;
				if (((previousValue != value) 
							|| (this._MucDoUuTien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MucDoUuTien.Entity = null;
						previousValue.DuAns.Remove(this);
					}
					this._MucDoUuTien.Entity = value;
					if ((value != null))
					{
						value.DuAns.Add(this);
						this._MaMucDoUuTien = value.MaMucDoUuTien;
					}
					else
					{
						this._MaMucDoUuTien = default(string);
					}
					this.SendPropertyChanged("MucDoUuTien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThanhVienNhomNhiemVus(ThanhVienNhomNhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = this;
		}
		
		private void detach_ThanhVienNhomNhiemVus(ThanhVienNhomNhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = null;
		}
		
		private void attach_ThanhVienNhomDuAns(ThanhVienNhomDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = this;
		}
		
		private void detach_ThanhVienNhomDuAns(ThanhVienNhomDuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MucDoQuanTrong")]
	public partial class MucDoQuanTrong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMucDoQuanTrong;
		
		private string _TenMucDoQuanTrong;
		
		private EntitySet<DuAn> _DuAns;
		
		private EntitySet<NhiemVu> _NhiemVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMucDoQuanTrongChanging(string value);
    partial void OnMaMucDoQuanTrongChanged();
    partial void OnTenMucDoQuanTrongChanging(string value);
    partial void OnTenMucDoQuanTrongChanged();
    #endregion
		
		public MucDoQuanTrong()
		{
			this._DuAns = new EntitySet<DuAn>(new Action<DuAn>(this.attach_DuAns), new Action<DuAn>(this.detach_DuAns));
			this._NhiemVus = new EntitySet<NhiemVu>(new Action<NhiemVu>(this.attach_NhiemVus), new Action<NhiemVu>(this.detach_NhiemVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMucDoQuanTrong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMucDoQuanTrong
		{
			get
			{
				return this._MaMucDoQuanTrong;
			}
			set
			{
				if ((this._MaMucDoQuanTrong != value))
				{
					this.OnMaMucDoQuanTrongChanging(value);
					this.SendPropertyChanging();
					this._MaMucDoQuanTrong = value;
					this.SendPropertyChanged("MaMucDoQuanTrong");
					this.OnMaMucDoQuanTrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMucDoQuanTrong", DbType="NVarChar(30)")]
		public string TenMucDoQuanTrong
		{
			get
			{
				return this._TenMucDoQuanTrong;
			}
			set
			{
				if ((this._TenMucDoQuanTrong != value))
				{
					this.OnTenMucDoQuanTrongChanging(value);
					this.SendPropertyChanging();
					this._TenMucDoQuanTrong = value;
					this.SendPropertyChanged("TenMucDoQuanTrong");
					this.OnTenMucDoQuanTrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MucDoQuanTrong_DuAn", Storage="_DuAns", ThisKey="MaMucDoQuanTrong", OtherKey="MaMucDoQuanTrong")]
		public EntitySet<DuAn> DuAns
		{
			get
			{
				return this._DuAns;
			}
			set
			{
				this._DuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MucDoQuanTrong_NhiemVu", Storage="_NhiemVus", ThisKey="MaMucDoQuanTrong", OtherKey="MaMucDoQuanTrong")]
		public EntitySet<NhiemVu> NhiemVus
		{
			get
			{
				return this._NhiemVus;
			}
			set
			{
				this._NhiemVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.MucDoQuanTrong = this;
		}
		
		private void detach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.MucDoQuanTrong = null;
		}
		
		private void attach_NhiemVus(NhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.MucDoQuanTrong = this;
		}
		
		private void detach_NhiemVus(NhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.MucDoQuanTrong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MucDoUuTien")]
	public partial class MucDoUuTien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMucDoUuTien;
		
		private string _TenMucDoUuTien;
		
		private EntitySet<DuAn> _DuAns;
		
		private EntitySet<NhiemVu> _NhiemVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMucDoUuTienChanging(string value);
    partial void OnMaMucDoUuTienChanged();
    partial void OnTenMucDoUuTienChanging(string value);
    partial void OnTenMucDoUuTienChanged();
    #endregion
		
		public MucDoUuTien()
		{
			this._DuAns = new EntitySet<DuAn>(new Action<DuAn>(this.attach_DuAns), new Action<DuAn>(this.detach_DuAns));
			this._NhiemVus = new EntitySet<NhiemVu>(new Action<NhiemVu>(this.attach_NhiemVus), new Action<NhiemVu>(this.detach_NhiemVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMucDoUuTien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMucDoUuTien
		{
			get
			{
				return this._MaMucDoUuTien;
			}
			set
			{
				if ((this._MaMucDoUuTien != value))
				{
					this.OnMaMucDoUuTienChanging(value);
					this.SendPropertyChanging();
					this._MaMucDoUuTien = value;
					this.SendPropertyChanged("MaMucDoUuTien");
					this.OnMaMucDoUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMucDoUuTien", DbType="NVarChar(10)")]
		public string TenMucDoUuTien
		{
			get
			{
				return this._TenMucDoUuTien;
			}
			set
			{
				if ((this._TenMucDoUuTien != value))
				{
					this.OnTenMucDoUuTienChanging(value);
					this.SendPropertyChanging();
					this._TenMucDoUuTien = value;
					this.SendPropertyChanged("TenMucDoUuTien");
					this.OnTenMucDoUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MucDoUuTien_DuAn", Storage="_DuAns", ThisKey="MaMucDoUuTien", OtherKey="MaMucDoUuTien")]
		public EntitySet<DuAn> DuAns
		{
			get
			{
				return this._DuAns;
			}
			set
			{
				this._DuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MucDoUuTien_NhiemVu", Storage="_NhiemVus", ThisKey="MaMucDoUuTien", OtherKey="MaMucDoUuTien")]
		public EntitySet<NhiemVu> NhiemVus
		{
			get
			{
				return this._NhiemVus;
			}
			set
			{
				this._NhiemVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.MucDoUuTien = this;
		}
		
		private void detach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.MucDoUuTien = null;
		}
		
		private void attach_NhiemVus(NhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.MucDoUuTien = this;
		}
		
		private void detach_NhiemVus(NhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.MucDoUuTien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _TenNhanVien;
		
		private string _DiaChiNhanVien;
		
		private System.Nullable<bool> _GioiTinhNhanVien;
		
		private System.Nullable<System.DateTime> _NgaySinhNhanVien;
		
		private string _MaChucVu;
		
		private EntitySet<ThanhVienNhomNhiemVu> _ThanhVienNhomNhiemVus;
		
		private EntitySet<Nhom> _Nhoms;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
		private EntitySet<ThanhVienNhom> _ThanhVienNhoms;
		
		private EntitySet<ThanhVienNhomDuAn> _ThanhVienNhomDuAns;
		
		private EntityRef<ChucVu> _ChucVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnDiaChiNhanVienChanging(string value);
    partial void OnDiaChiNhanVienChanged();
    partial void OnGioiTinhNhanVienChanging(System.Nullable<bool> value);
    partial void OnGioiTinhNhanVienChanged();
    partial void OnNgaySinhNhanVienChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhNhanVienChanged();
    partial void OnMaChucVuChanging(string value);
    partial void OnMaChucVuChanged();
    #endregion
		
		public NhanVien()
		{
			this._ThanhVienNhomNhiemVus = new EntitySet<ThanhVienNhomNhiemVu>(new Action<ThanhVienNhomNhiemVu>(this.attach_ThanhVienNhomNhiemVus), new Action<ThanhVienNhomNhiemVu>(this.detach_ThanhVienNhomNhiemVus));
			this._Nhoms = new EntitySet<Nhom>(new Action<Nhom>(this.attach_Nhoms), new Action<Nhom>(this.detach_Nhoms));
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			this._ThanhVienNhoms = new EntitySet<ThanhVienNhom>(new Action<ThanhVienNhom>(this.attach_ThanhVienNhoms), new Action<ThanhVienNhom>(this.detach_ThanhVienNhoms));
			this._ThanhVienNhomDuAns = new EntitySet<ThanhVienNhomDuAn>(new Action<ThanhVienNhomDuAn>(this.attach_ThanhVienNhomDuAns), new Action<ThanhVienNhomDuAn>(this.detach_ThanhVienNhomDuAns));
			this._ChucVu = default(EntityRef<ChucVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(30)")]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiNhanVien", DbType="NVarChar(50)")]
		public string DiaChiNhanVien
		{
			get
			{
				return this._DiaChiNhanVien;
			}
			set
			{
				if ((this._DiaChiNhanVien != value))
				{
					this.OnDiaChiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._DiaChiNhanVien = value;
					this.SendPropertyChanged("DiaChiNhanVien");
					this.OnDiaChiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinhNhanVien", DbType="Bit")]
		public System.Nullable<bool> GioiTinhNhanVien
		{
			get
			{
				return this._GioiTinhNhanVien;
			}
			set
			{
				if ((this._GioiTinhNhanVien != value))
				{
					this.OnGioiTinhNhanVienChanging(value);
					this.SendPropertyChanging();
					this._GioiTinhNhanVien = value;
					this.SendPropertyChanged("GioiTinhNhanVien");
					this.OnGioiTinhNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhNhanVien", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinhNhanVien
		{
			get
			{
				return this._NgaySinhNhanVien;
			}
			set
			{
				if ((this._NgaySinhNhanVien != value))
				{
					this.OnNgaySinhNhanVienChanging(value);
					this.SendPropertyChanging();
					this._NgaySinhNhanVien = value;
					this.SendPropertyChanged("NgaySinhNhanVien");
					this.OnNgaySinhNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", DbType="VarChar(10)")]
		public string MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThanhVienNhomNhiemVu", Storage="_ThanhVienNhomNhiemVus", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<ThanhVienNhomNhiemVu> ThanhVienNhomNhiemVus
		{
			get
			{
				return this._ThanhVienNhomNhiemVus;
			}
			set
			{
				this._ThanhVienNhomNhiemVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_Nhom", Storage="_Nhoms", ThisKey="MaNhanVien", OtherKey="MaTruongNhom")]
		public EntitySet<Nhom> Nhoms
		{
			get
			{
				return this._Nhoms;
			}
			set
			{
				this._Nhoms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThanhVienNhom", Storage="_ThanhVienNhoms", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<ThanhVienNhom> ThanhVienNhoms
		{
			get
			{
				return this._ThanhVienNhoms;
			}
			set
			{
				this._ThanhVienNhoms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThanhVienNhomDuAn", Storage="_ThanhVienNhomDuAns", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<ThanhVienNhomDuAn> ThanhVienNhomDuAns
		{
			get
			{
				return this._ThanhVienNhomDuAns;
			}
			set
			{
				this._ThanhVienNhomDuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien", Storage="_ChucVu", ThisKey="MaChucVu", OtherKey="MaChucVu", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._MaChucVu = value.MaChucVu;
					}
					else
					{
						this._MaChucVu = default(string);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThanhVienNhomNhiemVus(ThanhVienNhomNhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ThanhVienNhomNhiemVus(ThanhVienNhomNhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_Nhoms(Nhom entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_Nhoms(Nhom entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_ThanhVienNhoms(ThanhVienNhom entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ThanhVienNhoms(ThanhVienNhom entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_ThanhVienNhomDuAns(ThanhVienNhomDuAn entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ThanhVienNhomDuAns(ThanhVienNhomDuAn entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhiemVu")]
	public partial class NhiemVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhiemVu;
		
		private string _TenNhiemVu;
		
		private string _MoTaNhiemVu;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDauNhiemVu;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThucNhiemVu;
		
		private System.Nullable<bool> _HoanThanhNhiemVu;
		
		private string _MaMucDoQuanTrong;
		
		private string _MaMucDoUuTien;
		
		private EntitySet<ThanhVienNhomNhiemVu> _ThanhVienNhomNhiemVus;
		
		private EntityRef<MucDoQuanTrong> _MucDoQuanTrong;
		
		private EntityRef<MucDoUuTien> _MucDoUuTien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhiemVuChanging(string value);
    partial void OnMaNhiemVuChanged();
    partial void OnTenNhiemVuChanging(string value);
    partial void OnTenNhiemVuChanged();
    partial void OnMoTaNhiemVuChanging(string value);
    partial void OnMoTaNhiemVuChanged();
    partial void OnThoiGianBatDauNhiemVuChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauNhiemVuChanged();
    partial void OnThoiGianKetThucNhiemVuChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucNhiemVuChanged();
    partial void OnHoanThanhNhiemVuChanging(System.Nullable<bool> value);
    partial void OnHoanThanhNhiemVuChanged();
    partial void OnMaMucDoQuanTrongChanging(string value);
    partial void OnMaMucDoQuanTrongChanged();
    partial void OnMaMucDoUuTienChanging(string value);
    partial void OnMaMucDoUuTienChanged();
    #endregion
		
		public NhiemVu()
		{
			this._ThanhVienNhomNhiemVus = new EntitySet<ThanhVienNhomNhiemVu>(new Action<ThanhVienNhomNhiemVu>(this.attach_ThanhVienNhomNhiemVus), new Action<ThanhVienNhomNhiemVu>(this.detach_ThanhVienNhomNhiemVus));
			this._MucDoQuanTrong = default(EntityRef<MucDoQuanTrong>);
			this._MucDoUuTien = default(EntityRef<MucDoUuTien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhiemVu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhiemVu
		{
			get
			{
				return this._MaNhiemVu;
			}
			set
			{
				if ((this._MaNhiemVu != value))
				{
					this.OnMaNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._MaNhiemVu = value;
					this.SendPropertyChanged("MaNhiemVu");
					this.OnMaNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhiemVu", DbType="NVarChar(30)")]
		public string TenNhiemVu
		{
			get
			{
				return this._TenNhiemVu;
			}
			set
			{
				if ((this._TenNhiemVu != value))
				{
					this.OnTenNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._TenNhiemVu = value;
					this.SendPropertyChanged("TenNhiemVu");
					this.OnTenNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaNhiemVu", DbType="NVarChar(50)")]
		public string MoTaNhiemVu
		{
			get
			{
				return this._MoTaNhiemVu;
			}
			set
			{
				if ((this._MoTaNhiemVu != value))
				{
					this.OnMoTaNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._MoTaNhiemVu = value;
					this.SendPropertyChanged("MoTaNhiemVu");
					this.OnMoTaNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDauNhiemVu", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianBatDauNhiemVu
		{
			get
			{
				return this._ThoiGianBatDauNhiemVu;
			}
			set
			{
				if ((this._ThoiGianBatDauNhiemVu != value))
				{
					this.OnThoiGianBatDauNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDauNhiemVu = value;
					this.SendPropertyChanged("ThoiGianBatDauNhiemVu");
					this.OnThoiGianBatDauNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThucNhiemVu", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKetThucNhiemVu
		{
			get
			{
				return this._ThoiGianKetThucNhiemVu;
			}
			set
			{
				if ((this._ThoiGianKetThucNhiemVu != value))
				{
					this.OnThoiGianKetThucNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThucNhiemVu = value;
					this.SendPropertyChanged("ThoiGianKetThucNhiemVu");
					this.OnThoiGianKetThucNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoanThanhNhiemVu", DbType="Bit")]
		public System.Nullable<bool> HoanThanhNhiemVu
		{
			get
			{
				return this._HoanThanhNhiemVu;
			}
			set
			{
				if ((this._HoanThanhNhiemVu != value))
				{
					this.OnHoanThanhNhiemVuChanging(value);
					this.SendPropertyChanging();
					this._HoanThanhNhiemVu = value;
					this.SendPropertyChanged("HoanThanhNhiemVu");
					this.OnHoanThanhNhiemVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMucDoQuanTrong", DbType="VarChar(10)")]
		public string MaMucDoQuanTrong
		{
			get
			{
				return this._MaMucDoQuanTrong;
			}
			set
			{
				if ((this._MaMucDoQuanTrong != value))
				{
					if (this._MucDoQuanTrong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMucDoQuanTrongChanging(value);
					this.SendPropertyChanging();
					this._MaMucDoQuanTrong = value;
					this.SendPropertyChanged("MaMucDoQuanTrong");
					this.OnMaMucDoQuanTrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMucDoUuTien", DbType="VarChar(10)")]
		public string MaMucDoUuTien
		{
			get
			{
				return this._MaMucDoUuTien;
			}
			set
			{
				if ((this._MaMucDoUuTien != value))
				{
					if (this._MucDoUuTien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMucDoUuTienChanging(value);
					this.SendPropertyChanging();
					this._MaMucDoUuTien = value;
					this.SendPropertyChanged("MaMucDoUuTien");
					this.OnMaMucDoUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhiemVu_ThanhVienNhomNhiemVu", Storage="_ThanhVienNhomNhiemVus", ThisKey="MaNhiemVu", OtherKey="MaNhiemVu")]
		public EntitySet<ThanhVienNhomNhiemVu> ThanhVienNhomNhiemVus
		{
			get
			{
				return this._ThanhVienNhomNhiemVus;
			}
			set
			{
				this._ThanhVienNhomNhiemVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MucDoQuanTrong_NhiemVu", Storage="_MucDoQuanTrong", ThisKey="MaMucDoQuanTrong", OtherKey="MaMucDoQuanTrong", IsForeignKey=true)]
		public MucDoQuanTrong MucDoQuanTrong
		{
			get
			{
				return this._MucDoQuanTrong.Entity;
			}
			set
			{
				MucDoQuanTrong previousValue = this._MucDoQuanTrong.Entity;
				if (((previousValue != value) 
							|| (this._MucDoQuanTrong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MucDoQuanTrong.Entity = null;
						previousValue.NhiemVus.Remove(this);
					}
					this._MucDoQuanTrong.Entity = value;
					if ((value != null))
					{
						value.NhiemVus.Add(this);
						this._MaMucDoQuanTrong = value.MaMucDoQuanTrong;
					}
					else
					{
						this._MaMucDoQuanTrong = default(string);
					}
					this.SendPropertyChanged("MucDoQuanTrong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MucDoUuTien_NhiemVu", Storage="_MucDoUuTien", ThisKey="MaMucDoUuTien", OtherKey="MaMucDoUuTien", IsForeignKey=true)]
		public MucDoUuTien MucDoUuTien
		{
			get
			{
				return this._MucDoUuTien.Entity;
			}
			set
			{
				MucDoUuTien previousValue = this._MucDoUuTien.Entity;
				if (((previousValue != value) 
							|| (this._MucDoUuTien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MucDoUuTien.Entity = null;
						previousValue.NhiemVus.Remove(this);
					}
					this._MucDoUuTien.Entity = value;
					if ((value != null))
					{
						value.NhiemVus.Add(this);
						this._MaMucDoUuTien = value.MaMucDoUuTien;
					}
					else
					{
						this._MaMucDoUuTien = default(string);
					}
					this.SendPropertyChanged("MucDoUuTien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThanhVienNhomNhiemVus(ThanhVienNhomNhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.NhiemVu = this;
		}
		
		private void detach_ThanhVienNhomNhiemVus(ThanhVienNhomNhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.NhiemVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhom")]
	public partial class Nhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private string _MaTruongNhom;
		
		private EntitySet<ThanhVienNhomNhiemVu> _ThanhVienNhomNhiemVus;
		
		private EntitySet<ThanhVienNhom> _ThanhVienNhoms;
		
		private EntitySet<ThanhVienNhomDuAn> _ThanhVienNhomDuAns;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnMaTruongNhomChanging(string value);
    partial void OnMaTruongNhomChanged();
    #endregion
		
		public Nhom()
		{
			this._ThanhVienNhomNhiemVus = new EntitySet<ThanhVienNhomNhiemVu>(new Action<ThanhVienNhomNhiemVu>(this.attach_ThanhVienNhomNhiemVus), new Action<ThanhVienNhomNhiemVu>(this.detach_ThanhVienNhomNhiemVus));
			this._ThanhVienNhoms = new EntitySet<ThanhVienNhom>(new Action<ThanhVienNhom>(this.attach_ThanhVienNhoms), new Action<ThanhVienNhom>(this.detach_ThanhVienNhoms));
			this._ThanhVienNhomDuAns = new EntitySet<ThanhVienNhomDuAn>(new Action<ThanhVienNhomDuAn>(this.attach_ThanhVienNhomDuAns), new Action<ThanhVienNhomDuAn>(this.detach_ThanhVienNhomDuAns));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(30)")]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTruongNhom", DbType="VarChar(10)")]
		public string MaTruongNhom
		{
			get
			{
				return this._MaTruongNhom;
			}
			set
			{
				if ((this._MaTruongNhom != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruongNhomChanging(value);
					this.SendPropertyChanging();
					this._MaTruongNhom = value;
					this.SendPropertyChanged("MaTruongNhom");
					this.OnMaTruongNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_ThanhVienNhomNhiemVu", Storage="_ThanhVienNhomNhiemVus", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<ThanhVienNhomNhiemVu> ThanhVienNhomNhiemVus
		{
			get
			{
				return this._ThanhVienNhomNhiemVus;
			}
			set
			{
				this._ThanhVienNhomNhiemVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_ThanhVienNhom", Storage="_ThanhVienNhoms", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<ThanhVienNhom> ThanhVienNhoms
		{
			get
			{
				return this._ThanhVienNhoms;
			}
			set
			{
				this._ThanhVienNhoms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_ThanhVienNhomDuAn", Storage="_ThanhVienNhomDuAns", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<ThanhVienNhomDuAn> ThanhVienNhomDuAns
		{
			get
			{
				return this._ThanhVienNhomDuAns;
			}
			set
			{
				this._ThanhVienNhomDuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_Nhom", Storage="_NhanVien", ThisKey="MaTruongNhom", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.Nhoms.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.Nhoms.Add(this);
						this._MaTruongNhom = value.MaNhanVien;
					}
					else
					{
						this._MaTruongNhom = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThanhVienNhomNhiemVus(ThanhVienNhomNhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = this;
		}
		
		private void detach_ThanhVienNhomNhiemVus(ThanhVienNhomNhiemVu entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = null;
		}
		
		private void attach_ThanhVienNhoms(ThanhVienNhom entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = this;
		}
		
		private void detach_ThanhVienNhoms(ThanhVienNhom entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = null;
		}
		
		private void attach_ThanhVienNhomDuAns(ThanhVienNhomDuAn entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = this;
		}
		
		private void detach_ThanhVienNhomDuAns(ThanhVienNhomDuAn entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Email;
		
		private string _Password;
		
		private string _MaNhanVien;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(10)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhVienNhom")]
	public partial class ThanhVienNhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _MaNhanVien;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<Nhom> _Nhom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    #endregion
		
		public ThanhVienNhom()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			this._Nhom = default(EntityRef<Nhom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._Nhom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThanhVienNhom", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ThanhVienNhoms.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhoms.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_ThanhVienNhom", Storage="_Nhom", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public Nhom Nhom
		{
			get
			{
				return this._Nhom.Entity;
			}
			set
			{
				Nhom previousValue = this._Nhom.Entity;
				if (((previousValue != value) 
							|| (this._Nhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom.Entity = null;
						previousValue.ThanhVienNhoms.Remove(this);
					}
					this._Nhom.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhoms.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("Nhom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhVienNhomDuAn")]
	public partial class ThanhVienNhomDuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _MaDuAn;
		
		private string _MaNhanVien;
		
		private EntityRef<DuAn> _DuAn;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<Nhom> _Nhom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnMaDuAnChanging(string value);
    partial void OnMaDuAnChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    #endregion
		
		public ThanhVienNhomDuAn()
		{
			this._DuAn = default(EntityRef<DuAn>);
			this._NhanVien = default(EntityRef<NhanVien>);
			this._Nhom = default(EntityRef<Nhom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._Nhom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					if (this._DuAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDuAnChanging(value);
					this.SendPropertyChanging();
					this._MaDuAn = value;
					this.SendPropertyChanged("MaDuAn");
					this.OnMaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_ThanhVienNhomDuAn", Storage="_DuAn", ThisKey="MaDuAn", OtherKey="MaDuAn", IsForeignKey=true)]
		public DuAn DuAn
		{
			get
			{
				return this._DuAn.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn.Entity;
				if (((previousValue != value) 
							|| (this._DuAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn.Entity = null;
						previousValue.ThanhVienNhomDuAns.Remove(this);
					}
					this._DuAn.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhomDuAns.Add(this);
						this._MaDuAn = value.MaDuAn;
					}
					else
					{
						this._MaDuAn = default(string);
					}
					this.SendPropertyChanged("DuAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThanhVienNhomDuAn", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ThanhVienNhomDuAns.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhomDuAns.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_ThanhVienNhomDuAn", Storage="_Nhom", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public Nhom Nhom
		{
			get
			{
				return this._Nhom.Entity;
			}
			set
			{
				Nhom previousValue = this._Nhom.Entity;
				if (((previousValue != value) 
							|| (this._Nhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom.Entity = null;
						previousValue.ThanhVienNhomDuAns.Remove(this);
					}
					this._Nhom.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhomDuAns.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("Nhom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
